/*
    Generated by: https://patorjk.com/software/taag/

    DDDDDDDDDDDDD                    AAA                 RRRRRRRRRRRRRRRRR     RRRRRRRRRRRRRRRRR                    AAA             YYYYYYY       YYYYYYY
    D::::::::::::DDD                A:::A                R::::::::::::::::R    R::::::::::::::::R                  A:::A            Y:::::Y       Y:::::Y
    D:::::::::::::::DD             A:::::A               R::::::RRRRRR:::::R   R::::::RRRRRR:::::R                A:::::A           Y:::::Y       Y:::::Y
    DDD:::::DDDDD:::::D           A:::::::A              RR:::::R     R:::::R  RR:::::R     R:::::R              A:::::::A          Y::::::Y     Y::::::Y
      D:::::D    D:::::D         A:::::::::A               R::::R     R:::::R    R::::R     R:::::R             A:::::::::A         YYY:::::Y   Y:::::YYY
      D:::::D     D:::::D       A:::::A:::::A              R::::R     R:::::R    R::::R     R:::::R            A:::::A:::::A           Y:::::Y Y:::::Y   
      D:::::D     D:::::D      A:::::A A:::::A             R::::RRRRRR:::::R     R::::RRRRRR:::::R            A:::::A A:::::A           Y:::::Y:::::Y    
      D:::::D     D:::::D     A:::::A   A:::::A            R:::::::::::::RR      R:::::::::::::RR            A:::::A   A:::::A           Y:::::::::Y     
      D:::::D     D:::::D    A:::::A     A:::::A           R::::RRRRRR:::::R     R::::RRRRRR:::::R          A:::::A     A:::::A           Y:::::::Y      
      D:::::D     D:::::D   A:::::AAAAAAAAA:::::A          R::::R     R:::::R    R::::R     R:::::R        A:::::AAAAAAAAA:::::A           Y:::::Y       
      D:::::D     D:::::D  A:::::::::::::::::::::A         R::::R     R:::::R    R::::R     R:::::R       A:::::::::::::::::::::A          Y:::::Y       
      D:::::D    D:::::D  A:::::AAAAAAAAAAAAA:::::A        R::::R     R:::::R    R::::R     R:::::R      A:::::AAAAAAAAAAAAA:::::A         Y:::::Y       
    DDD:::::DDDDD:::::D  A:::::A             A:::::A     RR:::::R     R:::::R  RR:::::R     R:::::R     A:::::A             A:::::A        Y:::::Y       
    D:::::::::::::::DD  A:::::A               A:::::A    R::::::R     R:::::R  R::::::R     R:::::R    A:::::A               A:::::A    YYYY:::::YYYY    
    D::::::::::::DDD   A:::::A                 A:::::A   R::::::R     R:::::R  R::::::R     R:::::R   A:::::A                 A:::::A   Y:::::::::::Y    
    DDDDDDDDDDDDD     AAAAAAA                   AAAAAAA  RRRRRRRR     RRRRRRR  RRRRRRRR     RRRRRRR  AAAAAAA                   AAAAAAA  YYYYYYYYYYYYY    
                                                                                                                                 
*/

#pragma once

#include "ddefines.h"

typedef struct darray_memory_allocator
{
    void* (*allocate)(u64);
    void* (*reallocate)(void*, u64);
    void  (*free)(void*); 
} darray_memory_allocator;

typedef enum darray_sort_type_enum
{
    DARRAY_SORT_TYPE_MERGE_SORT,
    DARRAY_SORT_TYPE_QUICK_SORT,
} darray_sort_type_enum;

void * darray___create__empty(u64 initial_capacity, u64 type_size_in_bytes, darray_memory_allocator* allocator);
void * darray___create__from_carray(const void * carray, u64 length, u64 type_size_in_bytes, darray_memory_allocator* allocator);
void * darray___create__from_darray(const void * darray, darray_memory_allocator* allocator);
void   darray___insert__at(void ** darray, const void * element, u64 index);
void   darray___remove__at(void ** darray, u64 index);
void   darray___remove(void ** darray, const void * element);
void   darray___push(void** darray, const void * element);
void   darray___pop(void** darray, void* out_element);
void   darray___sort(void* darray, bool (*compare)(void*, void*), darray_sort_type_enum sort_type);
u64    darray___get__length(const void * darray);
u64    darray___get__capacity(const void * darray);


#if defined(DARRAY_IMPLEMENTATION)

#include <stdlib.h>
#include <assert.h>
#include <string.h>

#define DARRAY_DEFAULT_ALLOCATOR (darray_memory_allocator){ .allocate = malloc, .free = free, .reallocate = realloc }
#define _head_from_block(block) (((_darray_header*)block)-1)
#define _block_from_head(head) (void*)(head + 1)

typedef struct _darray_header
{
    darray_memory_allocator allocator;
    u64 capacity;
    u64 count;
    u64 type_size_in_bytes;
} _darray_header;

static void _darray___merge_sort(void *darray, u64 start, u64 end, bool (*compare)(void *, void *));


void * darray___create__empty(u64 initial_capacity, u64 type_size_in_bytes, darray_memory_allocator* allocator)
{
    darray_memory_allocator _allocator = (allocator == NULL) ? DARRAY_DEFAULT_ALLOCATOR : *allocator;
    
    _darray_header* header = _allocator.allocate(sizeof(_darray_header) + initial_capacity * type_size_in_bytes);
    
    header->allocator          = _allocator;
    header->capacity           = initial_capacity;
    header->count              = 0;
    header->type_size_in_bytes = type_size_in_bytes;
    
    return _block_from_head(header);
}

void * darray___create__from_carray(const void *carray, u64 length, u64 type_size_in_bytes, darray_memory_allocator *allocator)
{
    darray_memory_allocator _allocator = (allocator == NULL) ? DARRAY_DEFAULT_ALLOCATOR : *allocator;
    
    _darray_header* header = _allocator.allocate(sizeof(_darray_header) + length * type_size_in_bytes);
    
    header->allocator          = _allocator;
    header->capacity           = length;
    header->count              = length;
    header->type_size_in_bytes = type_size_in_bytes;
    
    void* block = _block_from_head(header);
    memcpy(block, carray, length * type_size_in_bytes);
    
    return block;
}

void * darray___create__from_darray(const void *darray, darray_memory_allocator *allocator)
{
    darray_memory_allocator _allocator = (allocator == NULL) ? DARRAY_DEFAULT_ALLOCATOR : *allocator;

    _darray_header* old_header = _head_from_block(darray);
    _darray_header* header = _allocator.allocate(sizeof(_darray_header) + old_header->capacity * old_header->type_size_in_bytes);

    memcpy(header, old_header, sizeof(_darray_header) + old_header->capacity * old_header->type_size_in_bytes);

    return _block_from_head(header);
}

void darray___insert__at(void ** darray, const void *element, u64 index)
{
    if (darray == NULL) return; // Silence error
    
    _darray_header * head = _head_from_block((*darray));

    if (head->count <= index) return; // Silence error
    
    if (head->capacity <= head->count + 1)
    {
        head->capacity *= 2;

        void* reallocation = head->allocator.reallocate(head, sizeof(_darray_header) + head->capacity * head->type_size_in_bytes);
        assert(reallocation != NULL);
        
        head = reallocation;
        *darray = _block_from_head(head);
    }

    void * dest = (*darray) + (index + 1) * head->type_size_in_bytes;
    void * src  = (*darray) +  index      * head->type_size_in_bytes;
    u64 amount  = (head->count - index)   * head->type_size_in_bytes;

    memmove(dest, src, amount);
    memcpy(src, element, head->type_size_in_bytes);

    head->count++;
}

void darray___remove__at(void ** darray, u64 index)
{
    _darray_header* head = _head_from_block((*darray));

    if (index >= head->count) return; // Silence error

    memmove(darray + index, darray + index + 1, (head->count - index - 1) *  head->type_size_in_bytes);

    head->count--;
    // TODO: Add realloc when head->count < head->capacity / 4
    // Dont forget to reasign darray to new reallocation
}

void darray___remove(void ** darray, const void *element)
{
    if (element == NULL) return; // Silence error
    
    _darray_header* head = _head_from_block((*darray));
    
    for (u64 i = 0; i < head->count; i+= head->type_size_in_bytes)
    {
        bool found = true;
        for (u64 j = 0; j < head->type_size_in_bytes; j++)
        {
            if (*(((char*)(*darray)) + i + j) != *(((char*)element) + j))
            {
                found = false;
                break;
            }
        }
        
        if (found)
        {
            memmove(darray + i, darray + i + 1, (head->count - i - 1) *  head->type_size_in_bytes);
            head->count--;
            // TODO: Add realloc when head->count < head->capacity / 4
            // Dont forget to reasign darray to new reallocation
            return;
        }
    }
}

void darray___push(void **darray, const void *element)
{
    if (darray == NULL) return; // Silence error
    
    _darray_header * head = _head_from_block((*darray));
    
    if (head->capacity <= head->count + 1)
    {
        head->capacity *= 2;

        void* reallocation = head->allocator.reallocate(head, sizeof(_darray_header) + head->capacity * head->type_size_in_bytes);
        assert(reallocation != NULL);
        
        head = reallocation;
        *darray = _block_from_head(head);
    }

    void * dest = (*darray) + head->count * head->type_size_in_bytes;

    memcpy(dest, element, head->type_size_in_bytes);

    head->count++;
}

void darray___pop(void **darray, void *out_element)
{
    if (out_element == NULL) return; // Silence error

    _darray_header* head = _head_from_block((*darray));


    memmove(out_element, darray + --head->count, head->type_size_in_bytes);

    head->count--;
    // TODO: Add realloc when head->count < head->capacity / 4
    // Dont forget to reasign darray to new reallocation
}

inline void darray___sort(void *darray, bool (*compare)(void *, void *), darray_sort_type_enum sort_type)
{
    switch (sort_type)
    {
        case DARRAY_SORT_TYPE_MERGE_SORT:
        {
            _darray_header * head = _head_from_block(darray);
            _darray___merge_sort(darray, 0, head->count ,compare);
        } break;
        case DARRAY_SORT_TYPE_QUICK_SORT:
        {
            _darray_header * head = _head_from_block(darray);
            qsort(darray, head->count, head->type_size_in_bytes , compare);
        } break;
        default: { } break;
    }
}

inline u64 darray___get__length(const void *darray)
{
    if (darray == NULL) return 0; // Silence error
    return _head_from_block(darray)->count;
}

inline u64 darray___get__capacity(const void *darray)
{
    if (darray == NULL) return 0; // Silence error
    return _head_from_block(darray)->capacity;
}

static void _darray___merge_sort(void *darray, u64 start, u64 end, bool (*compare)(void *, void *))
{
    assert(0 && "NOT IMPLEMENTED");
}

#endif
