/*
    Generated by: https://patorjk.com/software/taag/                                                                                                                                                                                                                                            

    DDDDDDDDDDDDD        LLLLLLLLLLL               IIIIIIIIII  NNNNNNNN        NNNNNNNN  KKKKKKKKK    KKKKKKK  EEEEEEEEEEEEEEEEEEEEEE  DDDDDDDDDDDDD            LLLLLLLLLLL               IIIIIIIIII     SSSSSSSSSSSSSSS   TTTTTTTTTTTTTTTTTTTTTTT
    D::::::::::::DDD     L:::::::::L               I::::::::I  N:::::::N       N::::::N  K:::::::K    K:::::K  E::::::::::::::::::::E  D::::::::::::DDD         L:::::::::L               I::::::::I   SS:::::::::::::::S  T:::::::::::::::::::::T
    D:::::::::::::::DD   L:::::::::L               I::::::::I  N::::::::N      N::::::N  K:::::::K    K:::::K  E::::::::::::::::::::E  D:::::::::::::::DD       L:::::::::L               I::::::::I  S:::::SSSSSS::::::S  T:::::::::::::::::::::T
    DDD:::::DDDDD:::::D  LL:::::::LL               II::::::II  N:::::::::N     N::::::N  K:::::::K   K::::::K  EE::::::EEEEEEEEE::::E  DDD:::::DDDDD:::::D      LL:::::::LL               II::::::II  S:::::S     SSSSSSS  T:::::TT:::::::TT:::::T
      D:::::D    D:::::D   L:::::L                   I::::I    N::::::::::N    N::::::N  KK::::::K  K:::::KKK    E:::::E       EEEEEE    D:::::D    D:::::D       L:::::L                   I::::I    S:::::S              TTTTTT  T:::::T  TTTTTT
      D:::::D     D:::::D  L:::::L                   I::::I    N:::::::::::N   N::::::N    K:::::K K:::::K       E:::::E                 D:::::D     D:::::D      L:::::L                   I::::I    S:::::S                      T:::::T        
      D:::::D     D:::::D  L:::::L                   I::::I    N:::::::N::::N  N::::::N    K::::::K:::::K        E::::::EEEEEEEEEE       D:::::D     D:::::D      L:::::L                   I::::I     S::::SSSS                   T:::::T        
      D:::::D     D:::::D  L:::::L                   I::::I    N::::::N N::::N N::::::N    K:::::::::::K         E:::::::::::::::E       D:::::D     D:::::D      L:::::L                   I::::I      SS::::::SSSSS              T:::::T        
      D:::::D     D:::::D  L:::::L                   I::::I    N::::::N  N::::N:::::::N    K:::::::::::K         E:::::::::::::::E       D:::::D     D:::::D      L:::::L                   I::::I        SSS::::::::SS            T:::::T        
      D:::::D     D:::::D  L:::::L                   I::::I    N::::::N   N:::::::::::N    K::::::K:::::K        E::::::EEEEEEEEEE       D:::::D     D:::::D      L:::::L                   I::::I           SSSSSS::::S           T:::::T        
      D:::::D     D:::::D  L:::::L                   I::::I    N::::::N    N::::::::::N    K:::::K K:::::K       E:::::E                 D:::::D     D:::::D      L:::::L                   I::::I                S:::::S          T:::::T        
      D:::::D    D:::::D   L:::::L         LLLLLL    I::::I    N::::::N     N:::::::::N  KK::::::K  K:::::KKK    E:::::E       EEEEEE    D:::::D    D:::::D       L:::::L         LLLLLL    I::::I                S:::::S          T:::::T        
    DDD:::::DDDDD:::::D  LL:::::::LLLLLLLLL:::::L  II::::::II  N::::::N      N::::::::N  K:::::::K   K::::::K  EE::::::EEEEEEEE:::::E  DDD:::::DDDDD:::::D      LL:::::::LLLLLLLLL:::::L  II::::::II  SSSSSSS     S:::::S        TT:::::::TT      
    D:::::::::::::::DD   L::::::::::::::::::::::L  I::::::::I  N::::::N       N:::::::N  K:::::::K    K:::::K  E::::::::::::::::::::E  D:::::::::::::::DD       L::::::::::::::::::::::L  I::::::::I  S::::::SSSSSS:::::S        T:::::::::T      
    D::::::::::::DDD     L::::::::::::::::::::::L  I::::::::I  N::::::N        N::::::N  K:::::::K    K:::::K  E::::::::::::::::::::E  D::::::::::::DDD         L::::::::::::::::::::::L  I::::::::I  S:::::::::::::::SS         T:::::::::T      
    DDDDDDDDDDDDD        LLLLLLLLLLLLLLLLLLLLLLLL  IIIIIIIIII  NNNNNNNN         NNNNNNN  KKKKKKKKK    KKKKKKK  EEEEEEEEEEEEEEEEEEEEEE  DDDDDDDDDDDDD            LLLLLLLLLLLLLLLLLLLLLLLL  IIIIIIIIII   SSSSSSSSSSSSSSS           TTTTTTTTTTT      

*/

#pragma once

#include "ddefines.h"

typedef struct dlinked_list_memory_allocator
{
    void * (*allocate)(u64);
    void * (*reallocate)(void*, u64);
    void   (*free)(void*);
} dlinked_list_memory_allocator;


typedef struct _dlinked_list_iterator* dlinked_list_iterator;
typedef struct _dlinked_list _dlinked_list; 
typedef struct _dlinked_list * dlinked_list;

// dlinked_list dlinked_list___create(u64 item_size_in_bytes, dlinked_list_memory_allocator* allocator);
// void         dlinked_list___push_back(dlinked_list list, void* item);
// void         dlinked_list___push_front(dlinked_list list, void* item);
// void         dlinked_list___pop_front(dlinked_list list, void** out_item);
// void         dlinked_list___pop_back(dlinked_list list, void** out_item);
// void         dlinked_list___remove(dlinked_list list, void * item_to_remove);
// void         dlinked_list___remove_at(dlinked_list list, u64 index, bool from_start, void ** out_item);
// void         dlinked_list___add_at(dlinked_list list, u64 index, bool from_start, void* item);
// void         dlinked_list___destroy(dlinked_list list);

// dlinked_list_iterator dlinked_list___iterator__create(dlinked_list list);
// void *                dlinked_list___iterator__get_value(dlinked_list_iterator iterator);
// void                  dlinked_list___iterator__destroy(dlinked_list list);
// void                  dlinked_list___iterator__next(dlinked_list_iterator* iterator);

#if defined(DLINKED_LIST_IMPLEMENTATION)
#include <stdlib.h>
#include <string.h>
#define DLINKED_LIST_DEFAULT_ALLOCATOR (dlinked_list_memory_allocator){ .allocate = malloc, .reallocate = realloc, .free = free }


typedef struct _dlinked_list_entry
{
    void * value;
    struct _dlinked_list_entry * prev; 
    struct _dlinked_list_entry * next; 
} _dlinked_list_entry;

typedef struct _dlinked_list_iterator
{
    _dlinked_list_entry current;
} _dlinked_list_iterator;

typedef struct _dlinked_list
{
    dlinked_list_memory_allocator allocator;
    u64 count;
    u64 item_size_in_bytes;
    _dlinked_list_entry * head;
    _dlinked_list_entry * tail;
} _dlinked_list; 


#endif