/* 
    Generated by: https://patorjk.com/software/taag/                                                                                                                                                        
                                                                                                                                                             
    DDDDDDDDDDDDD        DDDDDDDDDDDDD        EEEEEEEEEEEEEEEEEEEEEE  FFFFFFFFFFFFFFFFFFFFFF  IIIIIIIIII  NNNNNNNN        NNNNNNNN  EEEEEEEEEEEEEEEEEEEEEE     SSSSSSSSSSSSSSS 
    D::::::::::::DDD     D::::::::::::DDD     E::::::::::::::::::::E  F::::::::::::::::::::F  I::::::::I  N:::::::N       N::::::N  E::::::::::::::::::::E   SS:::::::::::::::S
    D:::::::::::::::DD   D:::::::::::::::DD   E::::::::::::::::::::E  F::::::::::::::::::::F  I::::::::I  N::::::::N      N::::::N  E::::::::::::::::::::E  S:::::SSSSSS::::::S
    DDD:::::DDDDD:::::D  DDD:::::DDDDD:::::D  EE::::::EEEEEEEEE::::E  FF::::::FFFFFFFFF::::F  II::::::II  N:::::::::N     N::::::N  EE::::::EEEEEEEEE::::E  S:::::S     SSSSSSS
      D:::::D    D:::::D   D:::::D    D:::::D   E:::::E       EEEEEE    F:::::F       FFFFFF    I::::I    N::::::::::N    N::::::N    E:::::E       EEEEEE  S:::::S            
      D:::::D     D:::::D  D:::::D     D:::::D  E:::::E                 F:::::F                 I::::I    N:::::::::::N   N::::::N    E:::::E               S:::::S            
      D:::::D     D:::::D  D:::::D     D:::::D  E::::::EEEEEEEEEE       F::::::FFFFFFFFFF       I::::I    N:::::::N::::N  N::::::N    E::::::EEEEEEEEEE      S::::SSSS         
      D:::::D     D:::::D  D:::::D     D:::::D  E:::::::::::::::E       F:::::::::::::::F       I::::I    N::::::N N::::N N::::::N    E:::::::::::::::E       SS::::::SSSSS    
      D:::::D     D:::::D  D:::::D     D:::::D  E:::::::::::::::E       F:::::::::::::::F       I::::I    N::::::N  N::::N:::::::N    E:::::::::::::::E         SSS::::::::SS  
      D:::::D     D:::::D  D:::::D     D:::::D  E::::::EEEEEEEEEE       F::::::FFFFFFFFFF       I::::I    N::::::N   N:::::::::::N    E::::::EEEEEEEEEE            SSSSSS::::S 
      D:::::D     D:::::D  D:::::D     D:::::D  E:::::E                 F:::::F                 I::::I    N::::::N    N::::::::::N    E:::::E                           S:::::S
      D:::::D    D:::::D   D:::::D    D:::::D   E:::::E       EEEEEE    F:::::F                 I::::I    N::::::N     N:::::::::N    E:::::E       EEEEEE              S:::::S
    DDD:::::DDDDD:::::D  DDD:::::DDDDD:::::D  EE::::::EEEEEEEE:::::E  FF:::::::FF             II::::::II  N::::::N      N::::::::N  EE::::::EEEEEEEE:::::E  SSSSSSS     S:::::S
    D:::::::::::::::DD   D:::::::::::::::DD   E::::::::::::::::::::E  F::::::::FF             I::::::::I  N::::::N       N:::::::N  E::::::::::::::::::::E  S::::::SSSSSS:::::S
    D::::::::::::DDD     D::::::::::::DDD     E::::::::::::::::::::E  F::::::::FF             I::::::::I  N::::::N        N::::::N  E::::::::::::::::::::E  S:::::::::::::::SS 
    DDDDDDDDDDDDD        DDDDDDDDDDDDD        EEEEEEEEEEEEEEEEEEEEEE  FFFFFFFFFFF             IIIIIIIIII  NNNNNNNN         NNNNNNN  EEEEEEEEEEEEEEEEEEEEEE   SSSSSSSSSSSSSSS   
                                                                                                                                                             
*/

#pragma once

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef unsigned long long u64;

typedef signed char i8;
typedef signed short i16;
typedef signed int i32;
typedef signed long long i64;

typedef float f32;
typedef double f64;

#if !defined(true) && !defined(false) && !defined(bool)
    typedef int _bool;
    #define bool _bool
    #define true 1
    #define false 0 
#endif

