
// Deafult `Hello world` welcome program generated by vs_code_c_template
// To run press: ctrl + shift + b => hit Build & run (debug).

#include <stdio.h>

int main(void)
{
    printf("Hello world\n");
    return 0;
}
